CREATE TABLE Customers (
CustomerID INT AUTO_INCREMENT PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
PhoneNumber VARCHAR(20) NOT NULL
);

CREATE TABLE Destinations (
DestinationID INT AUTO_INCREMENT PRIMARY KEY,
LocationName VARCHAR(60) NOT NULL,
Country VARCHAR(60) NOT NULL,
CostPerDay DECIMAL(10, 2) NOT NULL
);

CREATE TABLE Bookings (
BookingID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT NOT NULL,
DestinationID INT NOT NULL,
BookingDate DATE NOT NULL,
TravelDate DATE NOT NULL,
NumberOfDays INT NOT NULL,
CONSTRAINT FkCustomers
FOREIGN KEY(CustomerID)
REFERENCES Customers(CustomerID),
-- ON DELETE CASCADE
-- ON UPDATE CASCADE,
CONSTRAINT DestinationID
FOREIGN KEY(DestinationID)
REFERENCES Destinations(DestinationID)
-- ON DELETE CASCADE
-- ON UPDATE CASCADE
);

CREATE TABLE Payments (
PaymentID INT AUTO_INCREMENT PRIMARY KEY,
BookingID INT NOT NULL,
Amount DECIMAL(10,2) NOT NULL,
PaymentDate DATE NOT NULL,
PaymentMethod VARCHAR(50),
CONSTRAINT fk_bookings
FOREIGN KEY(BookingID)
REFERENCES Bookings(BookingID)
-- ON DELETE CASCADE
-- ON UPDATE CASCADE
);
