INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod ) VALUES (1, CalculatePaymentAmount(1), '2025-03-15', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (2, CalculatePaymentAmount(2), '2025-01-21', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (3, CalculatePaymentAmount(3), '2025-11-15', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (4, CalculatePaymentAmount(4), '2026-02-02', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (5, CalculatePaymentAmount(5), '2025-08-17', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (6, CalculatePaymentAmount(6), '2025-07-05', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (7, CalculatePaymentAmount(7), '2025-03-25', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (8, CalculatePaymentAmount(8), '2025-06-12', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (9, CalculatePaymentAmount(9), '2025-12-10', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (10, CalculatePaymentAmount(10), '2025-10-05', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (11, CalculatePaymentAmount(11), '2025-05-22', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (12, CalculatePaymentAmount(12), '2026-03-14', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (13, CalculatePaymentAmount(13), '2025-06-25', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (14, CalculatePaymentAmount(14), '2025-04-18', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (15, CalculatePaymentAmount(15), '2025-01-12', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (16, CalculatePaymentAmount(16), '2025-08-03', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (17, CalculatePaymentAmount(17), '2025-02-24', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (18, CalculatePaymentAmount(18), '2026-01-29', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (19, CalculatePaymentAmount(19), '2025-09-17', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (20, CalculatePaymentAmount(20), '2025-12-05', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (21, CalculatePaymentAmount(21), '2025-07-10', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (22, CalculatePaymentAmount(22), '2026-03-08', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (23, CalculatePaymentAmount(23), '2025-04-30', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (24, CalculatePaymentAmount(24), '2025-05-04', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (25, CalculatePaymentAmount(25), '2025-06-06', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (26, CalculatePaymentAmount(26), '2025-09-20', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (27, CalculatePaymentAmount(27), '2025-03-02', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (28, CalculatePaymentAmount(28), '2025-10-10', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (29, CalculatePaymentAmount(29), '2026-01-21', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (30, CalculatePaymentAmount(30), '2025-12-03', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (31, CalculatePaymentAmount(31), '2025-06-01', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (32, CalculatePaymentAmount(32), '2025-05-10', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (33, CalculatePaymentAmount(33), '2025-11-23', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (34, CalculatePaymentAmount(34), '2025-02-19', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (35, CalculatePaymentAmount(35), '2025-07-25', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (36, CalculatePaymentAmount(36), '2025-03-06', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (37, CalculatePaymentAmount(37), '2026-02-28', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (38, CalculatePaymentAmount(38), '2025-10-17', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (39, CalculatePaymentAmount(39), '2025-08-28', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (40, CalculatePaymentAmount(40), '2025-04-22', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (41, CalculatePaymentAmount(41), '2025-05-13', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (42, CalculatePaymentAmount(42), '2026-03-03', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (43, CalculatePaymentAmount(43), '2025-01-26', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (44, CalculatePaymentAmount(44), '2025-11-01', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (45, CalculatePaymentAmount(45), '2025-02-12', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (46, CalculatePaymentAmount(46), '2026-02-19', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (47, CalculatePaymentAmount(47), '2025-06-18', 'Debit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (48, CalculatePaymentAmount(48), '2025-09-05', 'Cash');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (49, CalculatePaymentAmount(49), '2025-10-25', 'Credit Card');
INSERT INTO Payments (BookingID, Amount, PaymentDate, PaymentMethod) VALUES (50, CalculatePaymentAmount(50), '2025-08-31', 'Debit Card');
