insert into tbl_songs (Title, Artist, Genre) values ('Golden Sunrise', 'Max Rhythm', 'electronic');
insert into tbl_songs (Title, Artist, Genre) values ('Twilight Tempest', 'Rocco Beat', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Willow', 'Sunny Melody', 'hip hop');
insert into tbl_songs (Title, Artist, Genre) values ('Eternal Echo', 'Nova Harmony', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Sapphire Skyline', 'Milo Crescendo', 'rock');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Willow', 'Phoenix Rhythm', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Moonlit Mirage', 'Lyra Chord', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Sapphire Skyline', 'Lyra Chord', 'country');
insert into tbl_songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Finn Solo', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Starlight Sonata', 'Aurora Melody', 'blues');
insert into tbl_songs (Title, Artist, Genre) values ('Enchanted Lullaby', 'Jazzie Keys', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Harbor Hymn', 'Violet Serenade', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Enchanted Evening', 'Willow Harmony', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Silent Symphony', 'Aurora Melody', 'folk');
insert into tbl_songs (Title, Artist, Genre) values ('Celestial Celebration', 'Violet Serenade', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Apollo Strum', 'pop');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Waves', 'Violet Serenade', 'jazz');
insert into tbl_songs (Title, Artist, Genre) values ('Golden Glow', 'Zara Cadence', 'folk');
insert into tbl_songs (Title, Artist, Genre) values ('Whispers in the Wind', 'Aurora Melody', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Twilight Tempest', 'Echo Jazz', 'blues');
insert into tbl_songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Jasper Jazz', 'pop');
insert into tbl_songs (Title, Artist, Genre) values ('Harbor Hymn', 'Rocco Beat', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Dreams of Tomorrow', 'Apollo Strum', 'rock');
insert into tbl_songs (Title, Artist, Genre) values ('Rhapsody in Blue', 'Jazzie Keys', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Mystical Mirage', 'Aria Harmony', 'electronic');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Windchimes', 'Stella Tempo', 'blues');
insert into tbl_songs (Title, Artist, Genre) values ('Rhapsody in Blue', 'Violet Serenade', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Celestial Celebration', 'Echo Jazz', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Twilight Tempest', 'Ziggy Beat', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Harbor Harmony', 'Sunny Melody', 'reggae');
insert into tbl_songs (Title, Artist, Genre) values ('Whirlwind Waltz', 'Luna Starlight', 'jazz');
insert into tbl_songs (Title, Artist, Genre) values ('Rhapsody in Blue', 'Aurora Melody', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Starry Night Sonata', 'Ryder Riff', 'punk');
insert into tbl_songs (Title, Artist, Genre) values ('Mystical Mirage', 'Violet Serenade', 'country');
insert into tbl_songs (Title, Artist, Genre) values ('Sapphire Serenade', 'Luna Lyric', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Aurora''s Anthem', 'Sunny Melody', 'rap');
insert into tbl_songs (Title, Artist, Genre) values ('Dreams of Tomorrow', 'Aurora Melody', 'pop');
insert into tbl_songs (Title, Artist, Genre) values ('Starry Night Sonata', 'Ziggy Beat', 'rap');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Waves', 'Finn Solo', 'electronic');
insert into tbl_songs (Title, Artist, Genre) values ('Rhapsody in Blue', 'Aurora Melody', 'folk');
insert into tbl_songs (Title, Artist, Genre) values ('Harmony of the Universe', 'Willow Harmony', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Luminous Lullaby', 'Max Rhythm', 'country');
insert into tbl_songs (Title, Artist, Genre) values ('Enchanted Lullaby', 'Ziggy Beat', 'metal');
insert into tbl_songs (Title, Artist, Genre) values ('Twilight Tempest', 'Lyra Chord', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Whispering Windchimes', 'Aurora Melody', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Silent Symphony', 'Ryder Riff', 'jazz');
insert into tbl_songs (Title, Artist, Genre) values ('Majestic Melody', 'Ryder Riff', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Dreams of Tomorrow', 'Rocco Beat', 'hip hop');
insert into tbl_songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Echo Jazz', 'indie');
insert into tbl_songs (Title, Artist, Genre) values ('Twilight Tango', 'Aria Harmony', 'indie');
